### ISSUE TITLE
 Vue Nested SFC breaks when vite press config is changed

### ISSUE THREAD

**Issue by louiss0** [HunYan-io/vite-plugin-vue-nested-sfc#9]
| library        | version        |
| -------------- | -------------- |
| vue-nested-sfc | 0.1.2          |
| vitepress      | 1.0.0-alpha.76 |

I was testing out `vue-nested-sfc` in a `vitepress` project where I decided to put the setting of `srcDir: 'pages'`. Ever since that happened I got this error.

```zsh
8:54:31 AM [vitepress] Internal server error: ENOENT: no such file or directory, open '/home/louiss/main/web-projects/ui/dummy-vitepress-project/pages/home/louiss/main/web-projects/ui/dummy-vitepress-project/layouts/Default.vue'
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at Object.getDescriptor (/home/louiss/main/web-projects/ui/dummy-vitepress-project/node_modules/.pnpm/vite-plugin-vue-nested-sfc@0.1.2_@vitejs+plugin-vue@4.2.3_vite@4.3.8_vue@3.3.4/node_modules/vite-plugin-vue-nested-sfc/dist/index.cjs:42:14)
      at Context.load (/home/louiss/main/web-projects/ui/dummy-vitepress-project/node_modules/.pnpm/vite-plugin-vue-nested-sfc@0.1.2_@vitejs+plugin-vue@4.2.3_vite@4.3.8_vue@3.3.4/node_modules/vite-plugin-vue-nested-sfc/dist/index.cjs:152:32)
      at Object.load (file:///home/louiss/main/web-projects/ui/dummy-vitepress-project/node_modules/.pnpm/vite@4.3.8/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:42892:46)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///home/louiss/main/web-projects/ui/dummy-vitepress-project/node_modules/.pnpm/vite@4.3.8/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53318:24)
```

**Minimal reproducible example**
www.github.com/louiss0/dummy-vitepress-project

**Comment by hunyan-io** [comment]
Fixed in `v0.1.3`
